
version: '3.3'

services:

  mysql-8.0.2:
    container_name: mysql-8.0.2
    build:
      context: ./services/mysql/8.0/alpine
    image: mysql:8.0.2-alpine
    volumes:
      - ./services/mysql/8.0/config:/etc/mysql
      - ./volumes/log/mysql:/var/log/mysql
      - ./volumes/data/mysql:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_USER: example
      MYSQL_PASSWORD: example
      MYSQL_DATABASE: example